JW_Backend/urls.py
from django.contrib import admin
from django.urls import include, path, re_path
from django.conf import settings
from django.conf.urls.static import static

from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)


schema_view = get_schema_view(
   openapi.Info(
      title="JerseyWorld API",
      default_version='v1',
      description="Test description",
      terms_of_service="https://www.google.com/policies/terms/",
      contact=openapi.Contact(email="contact@snippets.local"),
      license=openapi.License(name="BSD License"),
   ),
   public=True,
   permission_classes=[permissions.AllowAny],
)

urlpatterns = [

   # ------------------------------------------------------
   # ------------------ Main App---------------------------
   # ------------------------------------------------------
   path('', include('core.urls')),



   # ------------------------------------------------------
   # ------------------ Custom ----------------------------
   # ------------------------------------------------------
    path('admin/', admin.site.urls),
    path('api/',  include('api.urls')),

   # ------------------------------------------------------
   # ------------------ Custom ----------------------------
   # ------------------------------------------------------
    path('api/auth/', include('dj_rest_auth.urls')),

   # ------------------------------------------------------
   # ------------------ JWT ------------------------------
   # ------------------------------------------------------
    path('api/login/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),


   # ------------------------------------------------------
   # ------------------ SWAGGER ---------------------------
   # ------------------------------------------------------

    # SWAGGER UI
   re_path(r'^swagger(?P<format>\.json|\.yaml)$', schema_view.without_ui(cache_timeout=0), name='schema-json'),
   re_path(r'^swagger/$', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
   re_path(r'^redoc/$', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

api/urls.py
from django.urls import path

from .views import (
    api_index
)


app_name = 'api'

urlpatterns = [
    path('', api_index, name='index')
]

core/urls.py
from django.urls import path

from .views import (
    Index,
    JerseyStoreView,
    JerseyDetailView
)


app_name = 'core'


urlpatterns = [
    path(
        '',
        Index.as_view(),
        name='index'
    ),
    path(
        'store/<str:category>/',
        JerseyStoreView.as_view(),
        name='store'
    ),
    path(
        'jersey/<str:category>/<uuid:pk>/',
        JerseyDetailView.as_view(),
        name='jersey_detail'
    ),
]

core/models.py
from django.db import models

# Create your models here.

core/views.py
from typing import Any
from uuid import uuid4

from django.shortcuts import render
from django import http
from django.views.generic import TemplateView, ListView, DetailView

from api.models import (
    Jersey,
)


class Index(TemplateView):
    template_name = "core/index.html"

    def get(self, request: http.HttpRequest, *args: Any, **kwargs: Any) -> http.HttpResponse:
        if not (self.request.session.has_key('user_session')):
            self.request.session['user_session'] = str(uuid4())
        return super().get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context


class JerseyStoreView(ListView):
    template_name = 'core/store.html'

    def get_queryset(self):
        category: str = self.kwargs.get('category')
        queryset = Jersey.objects.filter(category__title=category)
        return queryset

    def get_context_data(self, **kwargs: any) -> dict[str, any]:
        category: str = self.kwargs.get('category')
        context = super().get_context_data(**kwargs)
        context['category'] =  category
        return context


class JerseyDetailView(DetailView):
    template_name = 'core/jersey_detail.html'
    model = Jersey

templates/core/inc/footer.html
  {% load static %}
  <!--************ Footer Starts ************* -->
  <footer class="my-5 container">
    <div class="row justify-content-evenly">
      <!-- logo -->
      <div class="col-sm-12 col-md-3">
        <div class="logo-wraper">
          <img src="{% static 'images/logo.png' %}" alt="JerseyWorld logo" />
        </div>
        <p class="text-muted mt-1">
          We provide you with quality jersey wears that bring out the beauty to
          honor your club
        </p>
      </div>

      <!-- Customer Service  -->
      <div class="col-sm-6 col-md-3 mt-2">
        <h3 class="h4">Customer Service</h3>
        <ul class="list-group m-0">
          <li class="list-group-item ml-0 border-0 px-0">
            <a href="" class="text-muted">Shipping</a>
          </li>
          <li class="list-group-item ml-0 border-0 px-0">
            <a href="" class="text-muted">Product Return</a>
          </li>
          <li class="list-group-item ml-0 border-0 px-0">
            <a href="" class="text-muted">Privacy Policy</a>
          </li>
          <li class="list-group-item ml-0 border-0 px-0">
            <a href="" class="text-muted">Terms & Conditions</a>
          </li>
        </ul>
      </div>

      <!-- Company  -->
      <div class="col-sm-6 col-md-3 mt-2">
        <h3 class="h4">Company</h3>
        <ul class="list-group m-0">
          <li class="list-group-item ml-0 border-0 px-0">
            <a href="" class="text-muted">Shipping</a>
          </li>
          <li class="list-group-item ml-0 border-0 px-0">
            <a href="" class="text-muted">Product Return</a>
          </li>
          <li class="list-group-item ml-0 border-0 px-0">
            <a href="" class="text-muted">Privacy Policy</a>
          </li>
          <li class="list-group-item ml-0 border-0 px-0">
            <a href="" class="text-muted">Terms & Conditions</a>
          </li>
        </ul>
      </div>

      <!-- Need Help  -->
      <div class="col-sm-6 col-md-3 mt-2">
        <h3 class="h4">Need Help?</h3>
        <ul class="list-group m-0">
          <li class="list-group-item ml-0 border-0 px-0">
            <div class="d-flex align-items-center">
              <img
                src="{% static 'icons/ic_baseline-support-agent.svg' %}"
                alt=""
              />
              <span class="text-muted  fw-bold">(+2348011224567)</span>
            </div>
          </li>
          <li class="list-group-item ml-0 border-0 px-0">
            <div class="d-flex justify-content-between align-items-center">
                <small>Monday - Saturday <br />
                  09:00am - 04:00pm</small>
              <div class="wh-container shadow">
                <div class="whatsapp-icon">
                  <img src="{% static 'icons/logos_whatsapp.svg' %}" alt="">
                </div>
                <span>Contact Us</span>
              </div>
            </div>
          </li>
          <li class="list-group-item ml-0 border-0 px-0">
            <span lass="text-muted"
              >Orders:
              <span class="text-decoration-underline"
                >orders@jerseyworld.co</span
              ></span
            >
          </li>
          <li class="list-group-item ml-0 border-0 px-0">
            <span lass="text-muted"
              >Returns:
              <span class="text-decoration-underline"
                >returns@jerseyworld.co</span
              ></span
            >
          </li>
        </ul>
      </div>
    </div>
  </footer>

  <!--************ Footer Ends ************* -->

  <!-- footer badge section -->
  <div class="text-center text-uppercase footer-bottom">
    <p>
      copyright (C)
      <script>
        document.write(new Date().getFullYear());
      </script>
      Jersey World. all right reserved
    </p>
  </div>

templates/core/inc/navigation.html
{% load static %}
<nav class="fixed-top w-100">
  <div class="nav-container container">
    <section class="lang-section">
      <span>
        Shipping to
        <div class="nav-flag"> 
          <img src="{% static 'images/flag.png' %}" alt="">
        </div> | English - NGN
        <i class="fa fa-solid_angle-down"></i>
      </span>
    </section>
  
    <a href="{% url 'core:index' %}">
      <section class="nav-logo">
        <img src="{% static 'images/logo.png' %}" alt="jersey world logo" />
      </section>
    </a>
  
    <section class="nav-items">
      <!-- search -->
      <div class="nav-item">
        <div class="fa fa-search fa-2x"></div>
      </div>
  
      <!-- Favorite -->
      <div class="nav-item">
        <i class="far fa-heart fa-2x"></i>
        <span class="nav-badge">1</span>
        <span class="nav-item-text">saved</span>
      </div>
  
      <!-- Cart -->
      <div class="nav-item">
        <i class="fa fa-shopping-cart fa-2x"></i>
        <span class="nav-badge">1</span>
        <span class="nav-item-text">cart</span>
      </div>
  
      <!-- User -->
      <div class="nav-item">
        <div class="nav-item-img-wrapper">
          <img src="{% static 'images/user.png' %}" alt="" />
        </div>
        <span class="nav-item-text">login</span>
      </div>
    </section>
  </div>
</nav>

templates/core/inc/subscription.html
{% load static %}
<section class="subscription my-5">
    <div class="sub-conent container">
      <div class="row justify-content-between align-items-center text-light">
        <div class="col-sm-12 col-md-5">
          <h4 class="text-capitalize mx-0 h3">
            Be Anothr Lucky Winner for the month!
          </h4>
          <p class="text-light fw-bold">
            <small
              >Stand a chance to get 50% off your favorite club Jersey this
              Month. You only need to enter your email stand teh changee to be
              the lucky winner fo this month
            </small>
          </p>

          <form action="" method="post">
            {% csrf_token %}
            <div class="sub-form">
              <input type="text" name="subscription_mail" class="" />
              <button type="submit" name="border-0 text-light fw-bold p-4">
                Signup
              </button>
            </div>
          </form>
        </div>

        <div class="col-sm-12 col-md-5">
          <div class="sub-image">
            <img src="{% static 'images/coupon 1.png' %}" alt="" />
          </div>
        </div>
      </div>
    </div>
  </section>