JW_Backend/urls.py
from django.contrib import admin
from django.urls import include, path, re_path
from django.conf import settings
from django.conf.urls.static import static

from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)


schema_view = get_schema_view(
   openapi.Info(
      title="JerseyWorld API",
      default_version='v1',
      description="Test description",
      terms_of_service="https://www.google.com/policies/terms/",
      contact=openapi.Contact(email="contact@snippets.local"),
      license=openapi.License(name="BSD License"),
   ),
   public=True,
   permission_classes=[permissions.AllowAny],
)

urlpatterns = [

   # ------------------------------------------------------
   # ------------------ Main App---------------------------
   # ------------------------------------------------------
   path('', include('core.urls')),



   # ------------------------------------------------------
   # ------------------ Custom ----------------------------
   # ------------------------------------------------------
    path('admin/', admin.site.urls),
    path('api/',  include('api.urls')),

   # ------------------------------------------------------
   # ------------------ Custom ----------------------------
   # ------------------------------------------------------
    path('api/auth/', include('dj_rest_auth.urls')),

   # ------------------------------------------------------
   # ------------------ JWT ------------------------------
   # ------------------------------------------------------
    path('api/login/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),


   # ------------------------------------------------------
   # ------------------ SWAGGER ---------------------------
   # ------------------------------------------------------

    # SWAGGER UI
   re_path(r'^swagger(?P<format>\.json|\.yaml)$', schema_view.without_ui(cache_timeout=0), name='schema-json'),
   re_path(r'^swagger/$', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
   re_path(r'^redoc/$', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

api/urls.py
from django.urls import path

from .views import (
    api_index
)


app_name = 'api'

urlpatterns = [
    path('', api_index, name='index')
]

core/urls.py
from django.urls import path

from .views import (
    Index,
    JerseyStoreView,
    JerseyDetailView
)


app_name = 'core'


urlpatterns = [
    path(
        '',
        Index.as_view(),
        name='index'
    ),
    path(
        'store/<str:category>/',
        JerseyStoreView.as_view(),
        name='store'
    ),
    path(
        'jersey/<str:category>/<uuid:pk>/',
        JerseyDetailView.as_view(),
        name='jersey_detail'
    ),
]

core/models.py
from django.db import models

# Create your models here.

core/views.py
from typing import Any
from uuid import uuid4

from django.shortcuts import render
from django import http
from django.views.generic import TemplateView, ListView, DetailView

from api.models import (
    Jersey,
)


class Index(TemplateView):
    template_name = "core/index.html"

    def get(self, request: http.HttpRequest, *args: Any, **kwargs: Any) -> http.HttpResponse:
        if not (self.request.session.has_key('user_session')):
            self.request.session['user_session'] = str(uuid4())
        return super().get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context


class JerseyStoreView(ListView):
    template_name = 'core/store.html'

    def get_queryset(self):
        category: str = self.kwargs.get('category')
        queryset = Jersey.objects.filter(category__title=category)
        return queryset

    def get_context_data(self, **kwargs: any) -> dict[str, any]:
        category: str = self.kwargs.get('category')
        context = super().get_context_data(**kwargs)
        context['category'] =  category
        return context


class JerseyDetailView(DetailView):
    template_name = 'core/jersey_detail.html'
    model = Jersey

templates/core/jersey_detail.html
{% extends 'core/template.html' %} {% load static %} {% block content %}

<main>
  <!-- Order  -->
  <section class="container my-5 py-5">
    <div class="row justify-content-between">
      <!--************ [LHS] ************* -->
      <div class="col-sm-12 col-md-6">
        <section class="preview-content">
          <!-- LHS -->
          <section class="preview-lhs">
            <div class="preview-min-image">
              <img src="{{ object.image_two.url }}" alt="" />
            </div>
            <div class="preview-min-image">
              <img src="{{ object.image_three.url }}" alt="" />
            </div>
            <div class="preview-min-image">
              <img src="{{ object.image_four.url }}" alt="" />
            </div>
            <div class="preview-min-image">
              <img src="{{ object.image_four.url }}" alt="" />
            </div>
          </section>

          <!-- RHS -->
          <section class="preview-rhs">
            <div class="discount-tag">
              <span class="text-light">-10% OFF</span>
            </div>
            <div class="shadow prev-action-container rounded-circle">
              <div class="fas fa-heart"></div>
            </div>
            <div class="shadow share-btn prev-action-container rounded-circle">
              <div class="fas fa-share text-success"></div>
            </div>
            <div class="card border-0">
              <img
                src="{{ object.main_image.url }}"
                alt=""
                class="card-image"
              />
            </div>
          </section>
        </section>
      </div>

      <!--************ [RHS] ************* -->
      <div class="col-sm-12 col-md-6">
        <!-- Title -->
        <section class="detail-title">
          <h2 class="h3">{{ object.title }}</h2>
          <p class="text-muted">
            <span class="stars">
              <i class="fas fa-star text-warning"></i>
              <i class="fas fa-star text-warning"></i>
              <i class="fas fa-star text-warning"></i>
              <i class="fas fa-star text-warning"></i>
              <i class="fas fa-star text-warning"></i>
            </span>
            <i class="fas fa-circle text-muted"></i>
            <span class="mx-2 fw-bold">
              <i class="fas fa-heart text-danger"></i>
              980 Loved It
            </span>
            <i class="fas fa-circle text-muted"></i>
            <span class="mx-2 fw-bold">
              <i class="fas fa-check text-success"></i>
              Authentic
            </span>
          </p>
        </section>

        <!-- Price -->
        <section class="prince">
          <span class="text-danger h3">NGN {{ object.price }}</span>
          <span class="text-muted text-srikethrough ms-4">
            <strike>NGN {{ object.price }}</strike>
          </span>
        </section>

        <p class="d-flex justify-content-between w-50 my-4">
          <span class="text-pirmary">Select size</span>
          <span class="blue"
            >See size guide
            <i class="far fa-question-circle text-danger"></i>
          </span>
        </p>

        <!-- Order Form -->
        <form action="">
          {% csrf_token %}
          <div class="sizes d-flex">
            <label class="size-container mx-2 p-1">
              XS
              <input type="radio" checked="checked" name="size" />
            </label>

            <label class="size-container mx-2 p-1">
              S
              <input type="radio" name="size" />
            </label>

            <label class="size-container mx-2 p-1">
              M <input type="radio" name='size' />
            </label>

            <label class="size-container mx-2 p-1">
              L <input type="radio" name='size' />
            </label>

            <label class="size-container mx-2 p-1">
              XL
              <input type="radio" name="size" />
            </label>
          </div>

          <section class="order-form mt-4 text-muted">
            <p class="fw-bold">Want this Jersey Customized?</p>
            <!-- Custom Name -->
            <div class="row align-items-center">
              <div class="col-sm-12 col-md-5">
                <input
                  type="text"
                  class="form-control"
                  name="custom_player"
                  placeholder="Add player name"
                />
              </div>
              <div class="col-sm-2 col-md-1">
                <span class="text-center">OR</span>
              </div>
              <div class="col">
                <div class="row">
                  <div class="col-6">
                    <input
                      type="text"
                      class="form-control"
                      name="custom_user_name"
                      placeholder="Add name"
                    />
                  </div>
                  <div class="col-6">
                    <input
                      type="text"
                      class="form-control"
                      name="custom_user_number"
                      placeholder="Add number"
                      inputmode="numeric"
                    />
                  </div>
                </div>
              </div>
            </div>

            <!-- quantity -->
            <div class="my-4">
              <p class="fw-bold blue">Quantity</p>
              <div class="d-flex quantity-box align-items-center">
                <button id="minusBtn" type="button">
                  <i class="fas fa-minus"></i>
                </button>
                <input
                  type="text"
                  name="quantity"
                  id="quantity-field"
                  inputmode="numeric"
                  placeholder="1"
                  value="1"
                />
                <button id="addBtn" type="button">
                  <i class="fas fa-plus"></i>
                </button>
              </div>
            </div>

            <div class="row mt-3">
              <div class="col-6">
                <button
                  id="add-to-cart-btn"
                  type="submit"
                  class="btn btn-block py-3"
                >
                  <!-- <i class="fas fa-cart text-light mx-2"></i> -->
                  <ion-icon name="cart-outline"></ion-icon>
                  <!-- <i class="fa fa-cart-shopping mx-2 text-light"></i> -->
                  Add to cart
                </button>
              </div>
              <div class="col-6">
                <button id="shop-now-btn" type="submit" class="btn btn-block py-3">
                  Buy Now
                </button>
              </div>
            </div>
          </section>
        </form>
      </div>
    </div>
  </section>

  <!-- Order Item -->
  <div class="description container mt-5 py-5">
    <div class="row justify-content-between">
      <div class="col-sm-12 col-md-4">
        <div class="specifications">
          <div class="small-title">Specifications</div>
          <table>
            <tr class="border-bottom">
              <td colspan="2">
                <span class="fw-bold">Team Jersey</span>
              </td>
              <td colspan="2">
                <span>{{ object.category.title }}</span>
              </td>
            </tr>

            <tr>
              <td colspan="2">
                <span class="fw-bold">Sport</span>
              </td>
              <td>
                <span>{{ object.category.title }}</span>
              </td>
            </tr>

            <tr>
              <td colspan="2">
                <span class="fw-bold">Brand</span>
              </td>
              <td>
                <span>{{ object.category.brand }}</span>
              </td>
            </tr>

            <tr>
              <td colspan="2">
                <span class="fw-bold">Gender</span>
              </td>
              <td>
                <span>{{ object.category.gender }}</span>
              </td>
            </tr>

            <tr>
              <td colspan="2">
                <span class="fw-bold">Condition</span>
              </td>
              <td>
                <span>New: A brand-new, unused, unopened, undamaged item</span>
              </td>
            </tr>
          </table>
        </div>
      </div>
      <div class="col-sm-12 col-md-7 mt-5">
        <div class="border-1 rounded-1">
          <ul class="nav nav-tabs">
            <li class="nav-item" role="presentation">
              <button
                class="nav-link active"
                id="home-tab"
                data-bs-toggle="tab"
                data-bs-target="#home"
                type="button"
                role="tab"
                aria-controls="home"
                aria-selected="true"
              >
                Description
              </button>
            </li>
            <li class="nav-item" role="presentation">
              <button
                class="nav-link"
                id="profile-tab"
                data-bs-toggle="tab"
                data-bs-target="#profile"
                type="button"
                role="tab"
                aria-controls="profile"
                aria-selected="false"
              >
                Shipping Info
              </button>
            </li>
            <li class="nav-item" role="presentation">
              <button
                class="nav-link"
                id="contact-tab"
                data-bs-toggle="tab"
                data-bs-target="#contact"
                type="button"
                role="tab"
                aria-controls="contact"
                aria-selected="false"
              >
                Warranty
              </button>
            </li>
            <li class="nav-item" role="presentation">
              <button
                class="nav-link"
                id="contact-tab"
                data-bs-toggle="tab"
                data-bs-target="#contact"
                type="button"
                role="tab"
                aria-controls="contact"
                aria-selected="false"
              >
                Return Policy
              </button>
            </li>
            <li class="nav-item" role="presentation">
              <button
                class="nav-link"
                id="contact-tab"
                data-bs-toggle="tab"
                data-bs-target="#contact"
                type="button"
                role="tab"
                aria-controls="contact"
                aria-selected="false"
              >
                Care For Jersey
              </button>
            </li>
            <li class="nav-item" role="presentation">
              <button
                class="nav-link"
                id="contact-tab"
                data-bs-toggle="tab"
                data-bs-target="#contact"
                type="button"
                role="tab"
                aria-controls="contact"
                aria-selected="false"
              >
                FAQ
              </button>
            </li>
          </ul>
          <div class="tab-content text-muted" id="myTabContent">
            <div
              class="tab-pane fade show active p-2 text-justify"
              id="home"
              role="tabpanel"
              aria-labelledby="home-tab"
            >
              {{ object.description }}
            </div>
            <div
              class="tab-pane fade p-2 text-justify"
              id="profile"
              role="tabpanel"
              aria-labelledby="profile-tab"
            >
              Lorem ipsum dolor sit amet consectetur, adipisicing elit. Earum
              repellendus modi in nostrum aliquam natus fugiat quo doloremque
              odio dicta!
            </div>
            <div
              class="tab-pane fade p-2 text-justify"
              id="contact"
              role="tabpanel"
              aria-labelledby="contact-tab"
            >
              Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ducimus
              perferendis aliquid laudantium soluta, incidunt tempore porro
              necessitatibus sapiente quo saepe.
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <!-- You May Also Like -->
  <div class="d-flex my-5 text-center align-items-center mx-auto w-25">
    <hr width="100" />
    <span class="fw-bold mx-3">You Might Also Like</span>
    <hr width="100" />
  </div>

  <!-- New Clothes -->
  <section class="container py-5 my-5">
    <div class="row justify-content-center align-items-center mt-5">
      <div class="col-sm-6 col-md-3">
        <div class="c-card p-2 rounded border">
          <!-- TODO: toggle icon color -->
          <!-- TODO: float-start hot-badge -->
          <a href="" class="float-end">
            <i class="far fa-heart fa-2x text-dark"></i>
          </a>
          <div class="c-img">
            <img src="{% static 'images/img-4.png' %}" alt="" class="w-100" />
          </div>
          <div class="c-card-text mt-4">
            <p class="text-wrap">
              Lorem ipsum dolor sit amet consectetur, elit
            </p>
            <!-- TODO: if price slash show previous price commented -->
            <span class="fw-bold">NGN 3,000 </span>
            <span class="fw-light text-muted text-decoration-line-through"
              >NGN 3,000</span
            >
          </div>
        </div>
      </div>
    </div>
  </section>

  <!--************ Subscription Starts ************* -->
  {% include 'core/inc/subscription.html' %}
  <!--************ Subscription Ends ************* -->

  <!--************ Footer Starts ************* -->
  {% include 'core/inc/footer.html' %}
  <!--************ Footer Ends ************* -->
</main>
{% endblock content %}

<!--************ Header Starts ************* -->
<!--************ Header Ends ************* -->

templates/core/store.html
{% extends 'core/template.html' %} {% load static %} {% block content %}

<main class="">
  <!--************ Filter Starts ************* -->
  <section class="store-filter container my-5 py-5">
    <div class="row justify-content-between align-items-center">
      <div class="col-sm-12 col-md-3">
        <h3 class="title">{{ category|title }} Jersey</h3>
        <small class="lead fw-bold text-muted"
          >Showing {{ objects.count }} results
        </small>
      </div>
      <div class="col-sm-12 col-md-2">
        <div class="d-flex align-items-center">
          <i class="bi bi-filter fa-2x mr-3"></i>
          <form action="" method="post">
            <select name="gender" id="" class="ml-3 p-3 w-100">
              <option value="male">Male</option>
              <option value="female">Female</option>
              <option value="both">Both</option>
            </select>
          </form>
        </div>
      </div>
    </div>
  </section>
  <!--************ Filter Ends ************* -->

  <!--************ Jersey Starts ************* -->
  {% if object_list.count < 1 %} {% include 'errors/item_not_found.html' %} 
  {% else %}
  <section class="my-5 pb-5 container">
    <div class="row justify-content-envenly mt-5">
      {% for object in object_list %}
      <div class="col-md-3 col-sm-6">
        <div class="s-card p-2 rounded border">
          <a href="" class="float-end">
            <i class="far fa-heart fa-2x text-dark"></i>
          </a>
          <div class="s-card-contents">
            <div class="c-img text-center">
              <img src="{{ object.main_image.url }}" alt="" />
            </div>
            <div class="c-card-text mt-4">
              <p class="text-wrap">{{ object.title }}</p>
              <span class="fw-bold">NGN {{ object.price }} </span>
              <span class="fw-light text-muted text-decoration-line-through"
                >NGN 3,000</span
              >
              <a
                href="{% url 'core:jersey_detail' object.category.title object.pk %}"
                class="btn btn-block btn-outline-danger px-5 py-2 shadow"
                style="display: block"
              >
                View
                <i class="fa fa-angle-right"></i>
              </a>
            </div>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
  </section>
  {% endif %}
  <!--************ Jersey Ends ************* -->

  <!--************ Subscription Starts ************* -->
  {% include 'core/inc/subscription.html' %}
  <!--************ Subscription Ends ************* -->

  <!--************ Footer Starts ************* -->
  {% include 'core/inc/footer.html' %}
  <!--************ Footer Ends ************* -->
</main>
{% endblock content %}

<!--************ Header Starts ************* -->
<!--************ Header Ends ************* -->

templates/core/template.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>JerseyWorld | {% block title %} Home {% endblock title %}</title>

    <!-- Styles  -->
    <link rel="stylesheet" href="{% static 'css/global.css' %}" />
    <link
      rel="stylesheet"
      href="{% static 'vendors/bootstrap/css/bootstrap.min.css' %}"
    />
    <link
      rel="stylesheet"
      href="{% static 'vendors/fontawesome/css/all.css' %}"
    />
    <link
      rel="stylesheet"
      href="{% static 'vendors/slick/slick/slick.css' %}"
    />
    <link
      rel="stylesheet"
      href="{% static 'vendors/slick/slick/slick-theme.css' %}"
    />
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css"
    />
    {% block styles %}{% endblock styles %}
  </head>
  <body>
    <!--************ Navigation Starts ************* -->
    {% include 'core/inc/navigation.html' %}
    <!--************ Navigation Ends ************* -->

    {% block content %}{% endblock content %}

    <!-- Scripts -->
    <script src="{% static 'js/jquery.js' %}"></script>
    <script src="{% static 'js/jquery_migrate.js' %}"></script>
    <script src="{% static 'vendors/bootstrap/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'vendors/slick/slick/slick.min.js' %}"></script>
    <script src="{% static 'js/global.js' %}"></script>
    <script
      type="module"
      src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"
    ></script>
    <script
      nomodule
      src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"
    ></script>
    {% block scripts %}{% endblock scripts %}
  </body>
</html>